name: minth
description: "Yet Another Minimalistic Theme"
version: 1.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fanci_playground: ^1.1.0
  fanci_dropdown: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true