name: fanci_playground
description: "UI for playground apps"
repository: https://github.com/astorDev/fanci/tree/main/playbase/flutter
version: 1.1.0

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true